# SPDX-FileCopyrightText: 2018-2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

spec-version: 0.31.0

name:                xrefcheck
version:             0.2
github:              serokell/xrefcheck
license:             MPL-2.0
license-file:        LICENSE
author:              Kostya Ivanov, Serokell
maintainer:          Serokell <hi@serokell.io>
copyright:           2018-2019 Serokell <https://serokell.io>
description:         Please see the README on GitHub at <https://github.com/serokell/xrefcheck#readme>

extra-source-files:
  - README.md
  - CHANGES.md

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - UndecidableInstances
  - ViewPatterns
  - TypeApplications
  - TypeOperators

ghc-options:
  - -Weverything
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wno-missing-safe-haskell-mode
  - -Wno-unsafe
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-export-lists
  - -Wno-all-missed-specialisations
  - -Wno-prepositive-qualified-module
  - -Wno-monomorphism-restriction

dependencies:
  - base

library:
  source-dirs: src

  generated-other-modules:
    - Paths_xrefcheck

  dependencies:
    - aeson
    - aeson-casing
    - async
    - bytestring
    - containers
    - cmark-gfm
    - data-default
    - directory-tree
    - directory
    - dlist
    - exceptions
    - filepath
    - raw-strings-qq
    - fmt
    - ftp-client
    - Glob
    - http-client
    - http-types
    - lens
    - pretty-terminal
    - modern-uri
    - mtl
    - o-clock
    - optparse-applicative
    - regex-tdfa
    - req
    - roman-numerals
    - tagsoup
    - text
    - text-metrics
    - th-lift-instances
    - time
    - universum
    - uri-bytestring
    - yaml

executables:
  xrefcheck:
    main: Main.hs
    source-dirs: exec
    generated-other-modules:
      - Paths_xrefcheck
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - xrefcheck
      - bytestring
      - universum
      - with-utf8

tests:
  xrefcheck-tests:
    main: Main.hs
    source-dirs: tests
    generated-other-modules:
      - Paths_xrefcheck
    dependencies:
      - case-insensitive
      - containers
      - firefly
      - hspec
      - hspec-expectations
      - QuickCheck
      - xrefcheck
      - bytestring
      - directory
      - fmt
      - http-types
      - HUnit
      - o-clock
      - regex-tdfa
      - time
      - universum
      - modern-uri
      - uri-bytestring
      - yaml
    build-tools:
      - hspec-discover

  links-tests:
    main: Main.hs
    source-dirs: links-tests
    build-tools: tasty-discover:tasty-discover
    generated-other-modules:
      - Paths_xrefcheck
    dependencies:
      - optparse-applicative
      - tagged
      - tasty
      - tasty-hunit
      - xrefcheck
      - universum
