# SPDX-FileCopyrightText: 2018-2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

spec-version: 0.31.0

name:                xrefcheck
version:             0.2.2
github:              serokell/xrefcheck
license:             MPL-2.0
license-file:        LICENSE
author:              Kostya Ivanov, Serokell
maintainer:          Serokell <hi@serokell.io>
copyright:           2018-2019 Serokell <https://serokell.io>
description:         Please see the README on GitHub at <https://github.com/serokell/xrefcheck#readme>

extra-source-files:
  - README.md
  - CHANGES.md

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -Weverything
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wno-missing-safe-haskell-mode
  - -Wno-unsafe
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-export-lists
  - -Wno-all-missed-specialisations
  - -Wno-prepositive-qualified-module
  - -Wno-monomorphism-restriction

  # This option avoids a warning on case-insensitive systems:
  # https://github.com/haskell/cabal/issues/4739
  # https://github.com/commercialhaskell/stack/issues/3918
  - -optP-Wno-nonportable-include-path

dependencies:
  - base >=4.14.3.0 && <5

library:
  source-dirs: src

  generated-other-modules:
    - Paths_xrefcheck

  dependencies:
    - aeson
    - aeson-casing
    - async
    - bytestring
    - cmark-gfm >= 0.2.5
    - containers
    - directory
    - dlist
    - filepath
    - fmt
    - ftp-client
    - Glob
    - http-client
    - http-types
    - lens
    - modern-uri
    - mtl
    - nyan-interpolation
    - o-clock
    - optparse-applicative
    - pretty-terminal
    - process
    - reflection
    - regex-tdfa
    - req
    - safe-exceptions
    - tagsoup
    - text
    - text-metrics
    - time
    - transformers
    - universum
    - uri-bytestring
    - yaml

executables:
  xrefcheck:
    main: Main.hs
    source-dirs: exec
    generated-other-modules:
      - Paths_xrefcheck
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - code-page
      - directory
      - universum
      - with-utf8
      - xrefcheck

tests:
  xrefcheck-tests:
    main: Main.hs
    source-dirs: tests
    build-tools: tasty-discover:tasty-discover
    generated-other-modules:
      - Paths_xrefcheck
    dependencies:
      - optparse-applicative
      - tagged
      - case-insensitive
      - cmark-gfm
      - containers
      - directory
      - firefly
      - http-types
      - modern-uri
      - nyan-interpolation
      - o-clock
      - reflection
      - regex-tdfa
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - time
      - universum
      - uri-bytestring
      - xrefcheck
      - yaml

  ftp-tests:
    main: Main.hs
    source-dirs: ftp-tests
    build-tools: tasty-discover:tasty-discover
    generated-other-modules:
      - Paths_xrefcheck
    dependencies:
      - optparse-applicative
      - tagged
      - tasty
      - tasty-hunit
      - universum
      - xrefcheck
