# SPDX-FileCopyrightText: 2018-2020 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

spec-version: 0.31.0

name:                xrefcheck
version:             0.1.2
github:              serokell/xrefcheck
license:             MPL-2.0
license-file:        LICENSE
author:              Kostya Ivanov, Serokell
maintainer:          Serokell <hi@serokell.io>
copyright:           2018-2019 Serokell <https://serokell.io>

extra-source-files:
- README.md
- CHANGES.md
- src-files/*

description:         Please see the README on GitHub at <https://github.com/serokell/xrefcheck#readme>

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - UndecidableInstances
  - ViewPatterns
  - TypeApplications
  - TypeOperators

ghc-options:
  - -Wall
  - -Wincomplete-record-updates

dependencies:
  - aeson
  - aeson-options
  - async
  - name: base
    mixin: [hiding (Prelude)]
    version: "< 4.15"
  - bytestring
  - containers
  - cmark-gfm
  - data-default
  - deepseq
  - directory-tree
  - directory
  - filepath
  - fmt
  - Glob
  - http-client
  - http-types
  - lens
  - pretty-terminal
  - modern-uri
  - mtl
  - o-clock
  - optparse-applicative
  - req
  - roman-numerals
  - template-haskell
  - text
  - text-metrics
  - th-lift-instances
  - th-utilities
  - name: universum
    mixin: [(Universum as Prelude), (Universum.Unsafe as Unsafe)]
  - yaml
  - with-utf8

library:
  source-dirs: src

  generated-other-modules:
  - Paths_xrefcheck

executables:
  xrefcheck:
    main:                Main.hs
    source-dirs:         exec
    generated-other-modules:
    - Paths_xrefcheck
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - xrefcheck

tests:
  xrefcheck-tests:
    main:                Main.hs
    source-dirs:         tests
    generated-other-modules:
    - Paths_xrefcheck
    dependencies:
    - xrefcheck
    - hspec
    - QuickCheck
    build-tools:
    - hspec-discover
