# SPDX-FileCopyrightText: 2018-2023 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-22.32

packages:
- .

extra-deps:
- nyan-interpolation-core-0.9.2
- nyan-interpolation-0.9.2
- ftp-client-0.5.1.6@sha256:fab127defe1efb165af58f84dbc0f57a39334e39cca9829946149b363a71d1ca,1694
