# SPDX-FileCopyrightText: 2023 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

name: master-update

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v3

      - name: Create a pre-release
        env:
          OVERWRITE_RELEASE: true
        # https://github.com/serokell/serokell.nix/blob/c1e2a33040438443c7721523e897db5e32a52a74/overlay/github.nix#L26
        run: |
          nix run .#github.autorelease -- "$(nix-build ./release)" "Automatic release on "$(date +\"%Y%m%d%H%M\")""

      - name: Push latest image to dockerhub
        run: |
          nix build -L .#docker-image
          nix shell .#skopeo -c ./scripts/upload-docker-image.sh "docker-archive:$(readlink result)" "docker://docker.io/serokell/xrefcheck:latest"
