# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

name: Danger

on: [pull_request]

jobs:
  run-danger-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - uses: MeilCli/danger-action@v5
      name: Instant checks
      with:
        install_path: 'vendor/bundle'
        danger_file: './danger/instant-checks.rb'
        danger_id: 'instant-checks'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_BOT_TOKEN }}
    - uses: MeilCli/danger-action@v5
      name: Premerge checks
      with:
        install_path: 'vendor/bundle'
        danger_file: './danger/premerge-checks.rb'
        danger_id: 'premerge-checks'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_BOT_TOKEN }}
